import '../models/emprestimo.dart';

class EmprestimoRepository {
  static List<Emprestimo> tabelaEmprestimo = [
    Emprestimo(
      idEmprestimo: 1,
      idLivro: 1,
      idAluno: 25039,
      fotoLivro: 'images/a_culpa_e_das_estrelas.jpg',
      tituloLivro: 'A Culpa é das Estrelas',
      autorLivro: 'John Green',
      nomeAluno: 'Rafael Rocha Silveira',
      telefoneAluno: '19 99665-4546',
      dataEmprestimo: '22/06/2023',
      dataRetirada: '22/06/2023',
      dataDevolucao: '25/06/2023',
      status: 'Aberto',
    ),
    Emprestimo(
      idEmprestimo: 2,
      idLivro: 2,
      idAluno: 25087,
      fotoLivro: 'images/a_liberdade_e_uma_luta_constante.jpg',
      tituloLivro: 'A Liberdade é uma Luta Constante',
      autorLivro: 'Angela Y. Davis',
      nomeAluno: 'Arthur Aparecido Marquesi Santana',
      telefoneAluno: '00 00000-0000',
      dataEmprestimo: '20/06/2023',
      dataRetirada: '21/06/2023',
      dataDevolucao: '30/06/2023',
      status: 'Aberto',
    ),
    Emprestimo(
      idEmprestimo: 3,
      idLivro: 3,
      idAluno: 25587,
      fotoLivro: 'images/cafe_com_deus_pai.jpg',
      tituloLivro: 'Café com Deus Pai',
      autorLivro: 'Junior Rostirola',
      nomeAluno: 'Gabriel Henrique',
      telefoneAluno: '00 00000-0000',
      dataEmprestimo: '20/06/2023',
      dataRetirada: '21/06/2023',
      dataDevolucao: '30/06/2023',
      status: 'Aberto',
    ),
    Emprestimo(
      idEmprestimo: 4,
      idLivro: 4,
      idAluno: 25479,
      fotoLivro: 'images/toda_poesia.jpg',
      tituloLivro: 'Toda Poesia',
      autorLivro: 'Paulo Leminski',
      nomeAluno: 'Gregory Augusto',
      telefoneAluno: '00 00000-0000',
      dataEmprestimo: '01/06/2023',
      dataRetirada: '01/06/2023',
      dataDevolucao: '10/06/2023',
      status: 'Vencido',
    ),
    Emprestimo(
      idEmprestimo: 5,
      idLivro: 5,
      idAluno: 25637,
      fotoLivro: 'images/onde_estao_as_flores.jpg',
      tituloLivro: 'Onde estão as flores?',
      autorLivro: 'Ilko Minev',
      nomeAluno: 'Danilo Bastos',
      telefoneAluno: '00 00000-0000',
      dataEmprestimo: '01/06/2023',
      dataRetirada: '01/06/2023',
      dataDevolucao: '10/06/2023',
      status: 'Vencido',
    ),
    Emprestimo(
      idEmprestimo: 6,
      idLivro: 6,
      idAluno: 25471,
      fotoLivro: 'images/o_cacador_de_pipas.jpg',
      tituloLivro: 'O Caçador de Pipas',
      autorLivro: 'Khaled Hosseini',
      nomeAluno: 'Rafael Polato',
      telefoneAluno: '00 00000-0000',
      dataEmprestimo: '01/06/2023',
      dataRetirada: '01/06/2023',
      dataDevolucao: '10/06/2023',
      status: 'Vencido',
    ),
  ];
}
